// Generated by CoffeeScript 1.7.1
(function() {
  var http, str, varname;

  http = require("http");

  str = "Hello CoffeeScript Again!9";

  varname = false;

  http.createServer(function(req, res) {
    res.writeHead(200);
    if (varname != null) {
      res.write('First ');
    }
    if (!false) {
      return res.end(str);
    }
  }).listen(4000);

}).call(this);

var temp;
